name: getx_hacker_news_api
description: NewsAPI app with GetX.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # GetX architecture
  get: ^3.12.1

  # newtork
  connectivity: ^0.4.9+3
  http: ^0.12.2

  # functional programming 
  dartz: ^0.9.2
  
  # local storage
  sqflite: ^1.3.1+1
  path_provider: ^1.6.18

  # helpers
  url_launcher: ^5.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # test
  test: any
  mockito: 

  # code linter
  effective_dart: ^1.2.0

  # icon generator
  flutter_launcher_icons: ^0.8.1
  # native splash generator
  flutter_native_splash: ^0.1.9

# flutter icons setup
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

# flutter splash screen setup
flutter_native_splash:
  image: assets/images/splash_icon.png
  color: "#FFEB3B"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/loading.jpg
    - assets/images/placeHolder.jpg
